/** @type {import('tailwindcss').Config} */
export default {
    content: [
        "./index.html",
        "./src/**/*.{js,ts,jsx,tsx}",
    ],
    darkMode: "class",
    theme: {
        extend: {
            colors: {
                "on-tertiary-fixed-variant": "#00513b",
                "surface-container-lowest": "#ffffff",
                "on-surface": "#181c1e",
                "surface-variant": "#e0e3e5",
                "secondary-fixed-dim": "#bcc7dd",
                "primary-fixed": "#d6e3ff",
                "primary-fixed-dim": "#adc7f7",
                "primary-container": "#1a365d",
                "surface-tint": "#455f88",
                "surface-dim": "#d7dadc",
                "inverse-primary": "#adc7f7",
                "secondary-container": "#d5e0f7",
                "outline": "#74777f",
                "on-secondary-fixed": "#111c2c",
                "tertiary-fixed-dim": "#8bd6b6",
                "tertiary-container": "#003e2c",
                "on-tertiary": "#ffffff",
                "secondary-fixed": "#d8e3fa",
                "inverse-surface": "#2d3133",
                "on-tertiary-fixed": "#002116",
                "tertiary": "#00261a",
                "outline-variant": "#c4c6cf",
                "on-primary-fixed": "#001b3c",
                "secondary": "#545f72",
                "surface-container": "#ebeef0",
                "background": "#f7fafc",
                "on-error-container": "#93000a",
                "surface-container-low": "#f1f4f6",
                "surface-container-highest": "#e0e3e5",
                "on-secondary": "#ffffff",
                "error-container": "#ffdad6",
                "tertiary-fixed": "#a6f2d1",
                "on-primary-fixed-variant": "#2d476f",
                "error": "#ba1a1a",
                "on-secondary-container": "#586377",
                "on-primary-container": "#86a0cd",
                "on-primary": "#ffffff",
                "inverse-on-surface": "#eef1f3",
                "surface": "#f7fafc",
                "on-tertiary-container": "#63ad8f",
                "on-background": "#181c1e",
                "on-surface-variant": "#43474e",
                "on-secondary-fixed-variant": "#3c475a",
                "on-error": "#ffffff",
                "primary": "#002045",
                "surface-container-high": "#e5e9eb",
                "surface-bright": "#f7fafc"
            },
            fontFamily: {
                "headline": ["Manrope"],
                "body": ["Inter"],
                "label": ["Inter"]
            },
            borderRadius: {
                "DEFAULT": "0.125rem", 
                "lg": "0.25rem", 
                "xl": "0.5rem", 
                "full": "0.75rem"
            },
        },
    },
    plugins: [],
}
